### ISSUE TITLE
File controls & Page Name occupies 30 % of visible area

### ISSUE THREAD

**Issue by nitish-17** [deathau/Notation-for-Obsidian#6]
Hi, I really like the look of the theme. But the file controls (i.e, edit,close,more option icons) and page name itself occupies 30 % of space on the screen. And when I split the page horizontally only 2 lines are visible as shown in the pics attached. Please make the top part narrow like all other themes so that I have more screen space to work with.  
<img width="463" alt="percent30waste" src="https://user-images.githubusercontent.com/62102673/123686960-fd70e000-d86d-11eb-858d-6b999a1baf8f.PNG">
<img width="468" alt="split" src="https://user-images.githubusercontent.com/62102673/123686975-019cfd80-d86e-11eb-805c-851da22b5a3d.PNG">

**Comment by nitish-17** [comment]
I'm using Windows 10

**Comment by gamedeviced** [comment]
Hi @nitish-17

you could create a css file to the folder _.obsidian/snippets_ in your vault and add the following code to reduce the height:

`.workspace-leaf-content[data-type=markdown] .view-header, .workspace-leaf.mod-active .workspace-leaf-content[data-type=markdown] .view-header { padding-top: 48px }`

(Adjust the value to your needs. As I'm on macOS you need to check the correct path for css snippets.)

Hope that helps!

**Comment by nitish-17** [comment]
Thanks @gamedeviced 👍
